class Strings {
  static String url = "http://www.amcadena.com/InstaFarma";
  static String consentimiento1= "No se otorgan garantías, promesas y/o representaciones de ningún tipo, expresas o implícitas, en cuanto a la naturaleza, estándar, exactitud o de otra manera de la información proporcionada en este sitio web ni a la idoneidad o de otra manera de la información a su circunstancia particular.";
  static String consentimiento2="No podemos y no garantizaremos que este sitio web esté libre de virus informáticos o cualquier otra cosa que tenga propiedades destructivas.";
  static String consentimiento3="No seremos responsables de ninguna pérdida o daño de cualquier naturaleza (directa, indirecta, consecuente u otra) ya sea que surja en contrato, agravio o de otra manera, que pueda surgir como resultado de su uso de (o incapacidad de uso) de este sitio web, o de su uso de (o no usar) la información de este sitio. Este sitio web proporciona enlaces a otros sitios web propiedad de terceros. El contenido de dichos sitios de terceros no está bajo nuestro control, y no podemos ni asumiremos la responsabilidad de la información o el contenido de estos. Los enlaces a dichos sitios de terceros no deben ser tomados como una aprobación por parte de Instapharma del sitio de terceros, o cualquier producto promovido, ofrecido o vendido en el sitio de terceros, ni que dichos sitios estén libres de virus informáticos o cualquier otra cosa que tenga propiedades destructivas. No podemos ni nos hacemos responsables de la recopilación o el uso de datos personales de ningún sitio de terceros. Además, no aceptaremos ninguna responsabilidad por la exactitud de los anuncios de terceros.";
  static String consentimiento4="No seremos responsables de ninguna pérdida o daño de cualquier naturaleza (directa, indirecta, consecuente u otra) ya sea que surja en contrato, agravio o de otra manera, que pueda surgir como resultado de su uso de (o incapacidad de uso) de este sitio web, o de su uso de (o no usar) la información de este sitio. Este sitio web proporciona enlaces a otros sitios web propiedad de terceros. El contenido de dichos sitios de terceros no está bajo nuestro control, y no podemos ni asumiremos la responsabilidad de la información o el contenido de estos. Los enlaces a dichos sitios de terceros no deben ser tomados como una aprobación por parte de Instapharma del sitio de terceros, o cualquier producto promovido, ofrecido o vendido en el sitio de terceros, ni que dichos sitios estén libres de virus informáticos o cualquier otra cosa que tenga propiedades destructivas. No podemos ni nos hacemos responsables de la recopilación o el uso de datos personales de ningún sitio de terceros. Además, no aceptaremos ninguna responsabilidad por la exactitud de los anuncios de terceros.";
  static String consentimiento5="No seremos responsables de ninguna pérdida o daño de cualquier naturaleza (directa, indirecta, consecuente u otra) ya sea que surja en contrato, agravio o de otra manera, que pueda surgir como resultado de su uso de (o incapacidad de uso) de este sitio web, o de su uso de (o no usar) la información de este sitio. Este sitio web proporciona enlaces a otros sitios web propiedad de terceros. El contenido de dichos sitios de terceros no está bajo nuestro control, y no podemos ni asumiremos la responsabilidad de la información o el contenido de estos. Los enlaces a dichos sitios de terceros no deben ser tomados como una aprobación por parte de Instapharma del sitio de terceros, o cualquier producto promovido, ofrecido o vendido en el sitio de terceros, ni que dichos sitios estén libres de virus informáticos o cualquier otra cosa que tenga propiedades destructivas. No podemos ni nos hacemos responsables de la recopilación o el uso de datos personales de ningún sitio de terceros. Además, no aceptaremos ninguna responsabilidad por la exactitud de los anuncios de terceros.";
  static String consentimiento6="INSTAPHARMA y el logotipo de Instapharma son marcas no comerciales no registradas de un APP desarrollada por un equipo investigador académico de la Universidad Autónoma de Bucaramanga.";
  
  
  
}